### PR TITLE
Add anonymous users

### PR DESCRIPTION
**Pull request by perpetuatingcuriosity**
Create anonymous users with GUID as email address

### CODE REVIEW

**Comment by mattl** [comment]
Here's a more standardized GUID function:

https://gist.github.com/mattl/638048b0b50ba12870ab

**Comment by perpetuatingcuriosity** [comment]
Kk updated! Looks like it’s working on my end.

**Comment by mattl** [comment]
So rather than merging this into my branch and resolving all the conflicts, just put this in a new branch and I'll remove mine.

**Comment by perpetuatingcuriosity** [comment]
feat-anonusers is there now. Let me know when it’s up!

**Pull request closed without merging**
